services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    # Frontend listens on port 80 inside the container (Dockerfile EXPOSE 80)

  - type: pserv
    name: service-1
    env: docker
    dockerfilePath: backend/services/service-1/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /

  - type: pserv
    name: service-2
    env: docker
    dockerfilePath: backend/services/service-2/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /

  - type: pserv
    name: service-3
    env: docker
    dockerfilePath: backend/services/service-3/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /
