services:
  - type: web
    name: frontend
    env: docker
    rootDir: frontend
    plan: starter
    autoDeploy: true
    healthCheckPath: /

  - type: pserv
    name: service-1
    env: docker
    rootDir: backend/services/service-1
    plan: starter
    autoDeploy: true

  - type: pserv
    name: service-2
    env: docker
    rootDir: backend/services/service-2
    plan: starter
    autoDeploy: true

  - type: pserv
    name: service-3
    env: docker
    rootDir: backend/services/service-3
    plan: starter
    autoDeploy: true
