services:
  - type: pserv
    name: service-1
    region: frankfurt
    env: docker
    rootDir: backend
    dockerfilePath: services/service-1/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - fromGroup: Groupito
      - key: PROXY_BASE_PATH
        value: /api/service-1
      - key: KAFKA_SERVICE_ID
        value: service-1
      - key: SERVICE_NAME
        value: service-1



  - type: pserv
    name: service-3
    region: frankfurt
    env: docker
    rootDir: backend
    dockerfilePath: services/service-3/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - fromGroup: Groupito

  - type: web
    name: frontend
    region: frankfurt
    env: docker
    rootDir: frontend
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SERVICE_1_URL
        value: http://service-1-pdn6:10000/
      - key: SERVICE_3_URL
        value: http://service-3-qjlp:8000/ 
