services:
  - type: pserv
    name: service-1
    region: frankfurt
    env: docker
    rootDir: backend
    dockerfilePath: services/service-1/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: KAFKA_BROKERS
        value: d2cd9it6crocq0g2mec0.any.ap-southeast-1.mpx.prd.cloud.redpanda.com:9092
      - key: KAFKA_USERNAME
        value: fvjohnny
      - key: KAFKA_PASSWORD
        value: "|h2(]YoYgWyZ]3]WNPW7iZVIAIHZBM"

  - type: pserv
    name: service-2
    region: frankfurt
    env: docker
    rootDir: backend
    dockerfilePath: services/service-2/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: KAFKA_BROKERS
        value: d2cd9it6crocq0g2mec0.any.ap-southeast-1.mpx.prd.cloud.redpanda.com:9092
      - key: KAFKA_USERNAME
        value: fvjohnny
      - key: KAFKA_PASSWORD
        value: "|h2(]YoYgWyZ]3]WNPW7iZVIAIHZBM"

  - type: pserv
    name: service-3
    region: frankfurt
    env: docker
    rootDir: backend
    dockerfilePath: services/service-3/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: KAFKA_BROKERS
        value: d2cd9it6crocq0g2mec0.any.ap-southeast-1.mpx.prd.cloud.redpanda.com:9092
      - key: KAFKA_USERNAME
        value: fvjohnny
      - key: KAFKA_PASSWORD
        value: "|h2(]YoYgWyZ]3]WNPW7iZVIAIHZBM"

  - type: web
    name: frontend
    region: frankfurt
    env: docker
    rootDir: frontend
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SERVICE_1_URL
        value: http://service-1-pdn6:10000/
      - key: SERVICE_2_URL
        value: http://service-2-e07k:10000/
      - key: SERVICE_3_URL
        value: http://service-3-qjlp:8000/ 
