services:
  - type: web
    name: frontend
    region: frankfurt
    env: docker
    rootDir: frontend
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SERVICE_1_URL
        value: http://service-1-m1mi:10000/
      - key: SERVICE_2_URL
        value: http://service-2-liyo:10000/
      - key: SERVICE_3_URL
        value: http://service-3-l8rf:8000/ 

  - type: pserv
    name: service-1
    region: frankfurt
    env: docker
    rootDir: backend/services/service-1
    plan: free
    autoDeploy: true

  - type: pserv
    name: service-2
    region: frankfurt
    env: docker
    rootDir: backend/services/service-2
    plan: free
    autoDeploy: true

  - type: pserv
    name: service-3
    region: frankfurt
    env: docker
    rootDir: backend/services/service-3
    plan: free
    autoDeploy: true
