services:
  service-1:
    build:
      context: ${PWD}/backend/services/service-1
      dockerfile: Dockerfile
    image: copy-signals-service-1:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"
    networks:
      - backend

  service-2:
    build:
      context: ${PWD}/backend/services/service-2
      dockerfile: Dockerfile
    image: copy-signals-service-2:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3002:3000"
    networks:
      - backend

  service-3:
    build:
      context: ${PWD}/backend/services/service-3
      dockerfile: Dockerfile
    image: copy-signals-service-3:latest
    environment:
      - NODE_ENV=production
      - PORT=8000
    ports:
      - "3003:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
