services:
  service-1:
    build:
      context: ${PWD}/backend/services/service-1
      dockerfile: Dockerfile
    image: copy-signals-service-1:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"
    networks:
      - backend

  service-2:
    build:
      context: ${PWD}/backend/services/service-2
      dockerfile: Dockerfile
    image: copy-signals-service-2:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3002:3000"
    networks:
      - backend

  service-3:
    build:
      context: ${PWD}/backend/services/service-3
      dockerfile: Dockerfile
    image: copy-signals-service-3:latest
    environment:
      - NODE_ENV=production
      - PORT=8000
    ports:
      - "3003:8000"
    networks:
      - backend

  frontend:
    build:
      context: ${PWD}/frontend
      dockerfile: Dockerfile
    image: copy-signals-frontend:latest
    ports:
      - "3000:80"
    networks:
      - backend
    environment:
      - SERVICE_1_URL=http://service-1:3000/
      - SERVICE_2_URL=http://service-2:3000/
      - SERVICE_3_URL=http://service-3:8000/

networks:
  backend:
    driver: bridge
