services:
  service-1:
    image: node:22-alpine
    working_dir: /app/services/service-1
    volumes:
      - ${PWD}/backend:/app
      - /app/services/service-1/node_modules
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - MESSAGING_BACKEND=${MESSAGING_BACKEND:-redis}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_USERNAME=${KAFKA_USERNAME:-}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD:-}
      - KAFKA_SERVICE_ID=service-1
      - PROXY_BASE_PATH=/api/service-1
      - MONGODB_URI=${MONGODB_URI:-mongodb://admin:admin123@mongodb:27017/service-1-db?authSource=admin}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-service-1-db}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_TLS=${REDIS_TLS:-false}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-service-1-db}
      - POSTGRES_SYNCHRONIZE=${POSTGRES_SYNCHRONIZE:-true}
      - POSTGRES_LOGGING=${POSTGRES_LOGGING:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    ports:
      - "3001:3000"
    networks:
      - backend
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy


  service-3:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ${PWD}/backend/services/service-3:/app
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=8000
      - MESSAGING_BACKEND=${MESSAGING_BACKEND:-redis}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_USERNAME=${KAFKA_USERNAME:-}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD:-}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_TLS=${REDIS_TLS:-false}
    ports:
      - "3003:8000"
    networks:
      - backend
    depends_on:
      kafka:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html
      - ${PWD}/frontend/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "3000:80"
    networks:
      - backend
    environment:
      - SERVICE_1_URL=http://service-1:3000/
      - SERVICE_3_URL=http://service-3:8000/
    depends_on:
      - service-1
      - service-3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: copysignals
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service-1-db
      PGDATA: /data/postgres
    volumes:
      - postgres_data_dev:/data/postgres
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data_dev:
  redis_data_dev:
  postgres_data_dev:
