services:
  - type: pserv
    name: service-1
    region: frankfurt
    env: docker
    rootDir: backend/services/service-1
    plan: starter
    autoDeploy: true

  - type: pserv
    name: service-2
    region: frankfurt
    env: docker
    rootDir: backend/services/service-2
    plan: starter
    autoDeploy: true

  - type: pserv
    name: service-3
    region: frankfurt
    env: docker
    rootDir: backend/services/service-3
    plan: starter
    autoDeploy: true

  - type: web
    name: frontend
    region: frankfurt
    env: docker
    rootDir: frontend
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SERVICE_1_URL
        value: http://service-1-pdn6:10000/
      - key: SERVICE_2_URL
        value: http://service-2-e07k:10000/
      - key: SERVICE_3_URL
        value: http://service-3-qjlp:8000/ 
